apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - name: game-2048
        image: ckdh0799/2048:latest
        ports:
        - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: game-2048
spec:
  type: NodePort 
  selector:
    app: game-2048
  ports:
  - port: 80
    nodePort: 30700
    targetPort: 80

